INFO:     Will watch for changes in these directories: ['/Users/ethanwang/CUHacksMario/CUHacksMario/backend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [20071] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/uvicorn/server.py", line 66, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/uvicorn/server.py", line 70, in serve
    await self._serve(sockets)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/uvicorn/server.py", line 77, in _serve
    config.load()
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/uvicorn/config.py", line 435, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/main.py", line 10, in <module>
    model = PPO.load("models/mario_ai_model.zip")
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/stable_baselines3/common/base_class.py", line 680, in load
    data, params, pytorch_variables = load_from_zip_file(
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 403, in load_from_zip_file
    file = open_path(load_path, "r", verbose=verbose, suffix="zip")
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/functools.py", line 877, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 240, in open_path_str
    return open_path_pathlib(pathlib.Path(path), mode, verbose, suffix)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 291, in open_path_pathlib
    return open_path_pathlib(path, mode, verbose, suffix)
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 272, in open_path_pathlib
    raise error
  File "/Users/ethanwang/CUHacksMario/CUHacksMario/backend/venv/lib/python3.9/site-packages/stable_baselines3/common/save_util.py", line 264, in open_path_pathlib
    return open_path(path.open("rb"), mode, verbose, suffix)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1242, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1110, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'models/mario_ai_model.zip.zip'
INFO:     Will watch for changes in these directories: ['/Users/ethanwang/CUHacksMario/CUHacksMario/backend']
ERROR:    [Errno 48] Address already in use
INFO:     Stopping reloader process [20071]
